version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers 
        environment: 
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: gohan-app_testing
          - DB_USERNAME: root
      - image: circleci/mysql:8.0.14
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: gohan-app_testing
          
    steps:
      - checkout 
      - run:
          name: "Node.js と npm の更新"
          command: |
            curl -sSL "https://nodejs.org/dist/v14.17.0/node-v14.17.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.17.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: 現行バージョンのノードのチェック
          command: node -v
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - run: composer install -n --prefer-dist 
      - run: npm ci 
      - run: npm run dev 
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate
      - run: 
          name: php test 
          command: vendor/bin/phpunit 
