version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers 
      - image: circleci/mysql:8.0.14
    steps:
      - checkout 
      - run:
          name: "Node.js と npm の更新"
          command: |
            curl -sSL "https://nodejs.org/dist/v14.17.0/node-v14.17.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: 現行バージョンのノードのチェック
          command: node -v
      - run: composer install -n --prefer-dist 
      - run: npm ci 
      - run: npm run dev 
      - run: 
          name: php test 
          command: vendor/bin/phpunit 
