version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers 
      - image: circleci/mysql:8.0.14
    steps:
      - checkout 
      - run: composer install -n --prefer-dist 
      - run: npm ci 
      - run: npm run dev 
      - run: 
          name: php test 
          command: vendor/bin/phpunit 
